(function(module) {
    
    module.factory('metadata', ['breeze', factory]);
    
    function factory(breeze) {
        return {
            fillStore: fillStore
        };
        
        function fillStore(store) {
            var keyGen = breeze.AutoGeneratedKeyType.Identity;
            var namespace = 'Goose.Model';
            var helper = new breeze.config.MetadataHelper(namespace, keyGen);
            var addType = function (type) { helper.addTypeToStore(store, type); };
             
            var DT = breeze.DataType;
            var BOOL = DT.Boolean;
            var DATE = DT.DateTime;
            var DECIMAL = DT.Decimal;
            var LUID = DT.Int32; // "Lookup" Id
            var ID = DT.MongoObjectId; // Root entity Id
            
            function addCountry() {
              addType({
                name: 'Country',
                dataProperties: {
                  _id: { type: ID, isPartOfKey: true },
                  name: { maxLength: 255, required: true },
                  region: {maxLength:255 },
                  cpi: { complex: 'cpi'},
                }
              });
            }
            
            function addCpi() {
              addType({
                name: 'cpi',
                isComplexType: true,
                dataProperties: {
                  
                }
              });
            }
            
            function addTodo() {
                addType({
                    name: 'Todo',
                    dataProperties: {
                        _id:        { type: ID, isPartOfKey: true},
                        text:       { maxLength: 255, required: true },
                        created:    { type: DATE, required: true, default: new Date(Date.now())},
                        done:       { type: BOOL, default: false},
                        tags:       { hasMany: true, default: [] }
                    }
                });
            }
        }
        
        function todoModel() {
            var DT = breeze.DataType;
            var BOOL = DT.Boolean;
            var DATE = DT.DateTime;
            var DECIMAL = DT.Decimal;
            var LUID = DT.Int32; // "Lookup" Id
            var ID = DT.MongoObjectId; // Root entity Id
            
            return {
                shortName: 'Todo',
                defaultResourceName: 'Todos',
                dataProperties: {
                    _id:         { dataType: ID, isPartOfKey: true },
                    text:       { maxLength: 255, isNullable: false },
                    created:    { dataType: DATE, isNullable: false, defaultValue: new Date(Date.now())},
                    done:       { dataType: BOOL, defaultValue: false},
                    tags:       { isScalar: false, defaultValue: [] }
                },
                autoGeneratedKeyType: breeze.AutoGeneratedKeyType.Identity
            };
        }
    }
    
})(angular.module('app'));